a=input("enter your name")
g=int(input("enter your age"))
d=float(input("enter your mark"))
e=bool(input("enter true if you are a student"))
print(a)
print(g)
print(d)
print(e)
print(type(a))
print(type(g))
print(type(d))
print(type(e))
